# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' original false
zstyle ':completion:*' use-compctl false
zstyle :compinstall filename '/home/d0ku/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=30000
setopt nomatch
unsetopt appendhistory autocd beep extendedglob notify
bindkey -v
# End of lines configured by zsh-newuser-install

# Prompt config

autoload colors
colors
export PS1="%~ %{%(#~$fg[red]~$fg[blue])%}%#%{$fg[default]%} "
export PS2=">"
export PROMPT="$PS1$PS2 "
